print("Day 1 - String Manipulation")
print("String Concatenation is done with the \"+\" sign.")
print('e.g. print("Hello " + " world")')
print("New lines can be created with a backslash and n.")
input("hello u")
input("hello u")
input("hello u")
input("hello u")
input("hello u")
input("hello u")
input("hello u")
